### ISSUE TITLE
Unable to mux with more than one topic

### ISSUE THREAD

**Issue by gseqBE** [ros-teleop/twist_mux#46]
I'm on Humble and have the mux package installed via apt.

I have two control topics /cmd_vel_joy_ps4 and /cmd_vel_joy_ui

```
twist_mux:
  ros__parameters:
    topics:
      joystick_ps4:
        topic   : cmd_vel_joy_ps4
        timeout : 0.5
        priority: 100
      joystick_ui:
        topic   : cmd_vel_joy_ui
        timeout : 0.5
        priority: 90
```

The mux only works if I have one of the above, but not both. 
I've confirmed that both work independently.

Any clues as to what I may have missed?

**Comment by bmagyar** [comment]
Are both the right type?

**Comment by gseqBE** [comment]
Yes, they both are the right type.

I can also echo both topics. I made sure to disconnect the joystick to make sure the UI passes through, for timeout testing.

![image](https://github.com/ros-teleop/twist_mux/assets/2365134/d422812d-ac25-478c-9fd9-1efc0047e5fe)

<img width="1359" alt="image" src="https://github.com/ros-teleop/twist_mux/assets/2365134/1cf5f314-8d95-4b3f-a181-eb68049d9dfa">

**Comment by gseqBE** [comment]
@bmagyar 
An update:
I uninstalled ros2-humble-twisy-mux package, cloned the rolling branch of twist mux.
I'm able to get it running with two control topics.

Any reason why the humble package would  not work?

**Comment by Rick-v-E** [comment]
I am experiencing the same problem using `humble`, both with the `apt` installed package as the current `rolling` version from GIT. `twist-mux` is only working when there is one topic in my config file: 

```yaml
twist_mux:
  ros__parameters:
    topics:
      external:
        topic   : cmd_vel
        timeout : 0.5
        priority: 1
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255
```

When I add a second topic to the config file, `twist-mux` does not publish anymore:

```yaml
twist_mux:
  ros__parameters:
    topics:
      joy:
        topic   : joy_vel
        timeout : 0.5
        priority: 10
      external:
        topic   : cmd_vel
        timeout : 0.5
        priority: 1
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255
```

From `/diagnostics`, I get:

```
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: ''
status:
- level: "\0"
  name: 'twist_mux: Twist mux status'
  message: ok
  hardware_id: none
  values:
  - key: velocity topics.external
    value: ' unmasked (listening to cmd_vel @ 0.500000s with priority #1)'
  - key: velocity topics.joy
    value: ' unmasked (listening to joy_vel @ 0.500000s with priority #10)'
  - key: lock locks.e_stop
    value: ' free (listening to e_stop @ 0.000000s with priority #255)'
  - key: current priority
    value: '0'
  - key: loop time in [sec]
    value: '0'
  - key: data age in [sec]
    value: '0'
```

Last year, the same config file using `twist-mux` on `humble` worked fine. However, not a lot has been changed to this package in meantime. Any clue how to fix this?
