### ISSUE TITLE
Doesn't seem to parse config properly at all

### ISSUE THREAD

**Issue by drozzy** [ros-teleop/twist_mux#56]
If I pass a config file, it complains about timeout being a double....

---
twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
    -
      name    : navigation
      topic   : nav_vel
      timeout : 0.5
      priority: 10
    -
      name    : joystick
      topic   : joy_vel
      timeout : 0.5
      priority: 100
    -
      name    : keyboard
      topic   : key_vel
      timeout : 0.5
      priority: 90
    -
      name    : tablet
      topic   : tab_vel
      timeout : 0.5
      priority: 100
    

libc++abi: terminating due to uncaught exception of type rclcpp::exceptions::RCLInvalidROSArgsError: failed to initialize rcl: Couldn't parse params file: '--params-file /Users/andriydrozdyuk/1.projects/arp1/ros/arp1_ros/install/arp1_ros/share/arp1_ros/config/twist_mux_params.yaml'. Error: Sequence should be of same type. Value type 'double' do not belong at line_num 9, at /Users/runner/conda-bld/bld/rattler-build_ros-jazzy-rcl-yaml-param-parser_1735936132/work/ros-jazzy-rcl-yaml-param-parser/src/work/src/parse.c:393, at /Users/runner/conda-bld/bld/rattler-build_ros-jazzy-rcl_1735937191/work/ros-jazzy-rcl/src/work/src/rcl/arguments.c:417
[ros2run]: Abort trap: 6

**Comment by fbottarel** [comment]
@drozzy I believe you might have a formatting issue. 

Try setting your config file to something like

```yaml

twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 10
      joy_teleop:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
      gui_teleop:
        topic   : cmd_vel_gui
        timeout : 0.5
        priority: 90
```

**Comment by aserbremen** [comment]
This still doesnt work properly:

Example config: 

```yaml
twist_mux: 
  ros__parameters:
    use_stamped: false
    topics:
      navigation: 
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 40
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 50
```

Error on ubuntu 24 and ROS2 jazzy:

```
[twist_mux-3] [INFO] [1743071493.072003227] [twist_mux]: Topic handler 'topics.joystick' subscribed to topic 'cmd_vel_joy': timeout = 0.500000s , priority = 50.
[twist_mux-3] [INFO] [1743071493.072614432] [twist_mux]: Topic handler 'topics.navigation' subscribed to topic 'cmd_vel_nav': timeout = 0.500000s , priority = 40.
[twist_mux-3] [FATAL] [1743071493.072891538] [twist_mux]: Error parsing params 'topics':
[twist_mux-3] 	could not load parameter 'topics.topic'. (namespace: /)
[twist_mux-3] terminate called after throwing an instance of 'twist_mux::ParamsHelperException'
[twist_mux-3]   what():  could not load parameter 'topics.topic'. (namespace: /)
[ERROR] [twist_mux-3]: process has died [pid 70220, exit code -6, cmd '/opt/ros/jazzy/lib/twist_mux/twist_mux --ros-args -r __node:=twist_mux --params-file /home/vamexcni/code/vamex/cni_ws/install/cni_bringup/share/cni_bringup/config/atlas/twist_mux.yaml'].
```
