### ISSUE TITLE
Example crashes without parameter in config

### ISSUE THREAD

**Issue by fbottarel** [ros-teleop/twist_mux#57]
Current launch configuration of the example does not work. I suspect the culprit is the absence of the `use_stamped` parameter in the YAML config file. 

**Branch: rolling**
**How to reproduce:**
```shell
sudo apt install ros-jazzy-twist-mux
ros2 launch twist_mux twist_mux_launch.py
[INFO] [launch]: All log files can be found below /home/vscode/.ros/log/2025-02-12-12-46-45-755957-docker-desktop-54858
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [twist_mux-1]: process started with pid [54861]
[INFO] [twist_marker-2]: process started with pid [54862]
[INFO] [joystick_relay.py-3]: process started with pid [54863]
[twist_mux-1] terminate called after throwing an instance of 'twist_mux::ParamsHelperException'
[twist_mux-1]   what():  could not load parameter 'use_stamped'. (namespace: /)
[ERROR] [twist_mux-1]: process has died [pid 54861, exit code -6, cmd '/opt/ros/jazzy/lib/twist_mux/twist_mux --ros-args --params-file /tmp/launch_params_4cjkk2ru --params-file /opt/ros/jazzy/share/twist_mux/config/twist_mux_locks.yaml --params-file /opt/ros/jazzy/share/twist_mux/config/twist_mux_topics.yaml -r /cmd_vel_out:=twist_mux/cmd_vel'].

**Comment by AhmedZeer** [comment]
EDIT:

I have seen your answer elsewhere 👍 
It **works** like so if anyone is facing the same problem :
```yaml
twist_mux:
  ros__parameters:
    use_stamped: true   ## This is mandatory !
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
        use_stamped: false
      keyboard:
        topic   : cmd_vel_keyboard
        timeout : 0.5
        priority: 100
        use_stamped: false
```

----
Same problem with Jazzy.
Doesn't work even with the following yaml file : 
```yaml
twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
        use_stamped: false
      keyboard:
        topic   : cmd_vel_keyboard
        timeout : 0.5
        priority: 100
        use_stamped: false

```
